#!/bin/bash

showHelp () {
  local scriptname="$(basename $0)"
  echo "Example usage and output: 
\$ $scriptname Voorschoten 
Voorschoten 🚲 1
Or,
\$ $scriptname Leiden
Leiden Centraal, Centrumzijde 🚲 89
Leiden Centraal,Uitgang LUMC 🚲 297
Leiden de Vink 🚲 3
" && exit 1

}

bikeAmount () {
  code="$1"
  a=$(curl -s "https://ovfietsbeschikbaar.nl/locatie/$code" | grep span | grep text-primary | grep -o ">[0-9]*<" | sed -E 's/(<|>)//g')
  echo "🚲 $a"
}
searchLocation() {
  curl -s "https://ovfietsbeschikbaar.nl/locaties" |
    grep locatie |
    grep -i "$1" |
    grep "</a>" |
    while IFS= read -r line; do
      name=$(echo "$line" | cut -d ">" -f2 | sed 's/<\/a//g')
      code=$(echo "$line" | grep -o 'locatie/[a-z0-9]*' | cut -d "/" -f2)
      bikes=$(bikeAmount "$code")
      echo "$name $bikes"
    done
}

if [ ! -n "$1" ]; then
  showHelp && exit 1
fi 

searchLocation "$1"
