#!/bin/bash

showHelp() {
    cat << EOF
Usage: $(basename "$0") [OPTIONS] SEARCH_TERM

}

bikeAmount () {
  code="$1"
  a=$(curl -s "https://ovfietsbeschikbaar.nl/locatie/$code" | grep span | grep text-primary | grep -o ">[0-9]*<" | sed -E 's/(<|>)//g')
  echo "🚲 $a"
}
searchLocation() {
  curl -s "https://ovfietsbeschikbaar.nl/locaties" |
    grep locatie |
    grep -i "$1" |
    grep "</a>" |
    while IFS= read -r line; do
      name=$(echo "$line" | cut -d ">" -f2 | sed 's/<\/a//g')
      code=$(echo "$line" | grep -o 'locatie/[a-z0-9]*' | cut -d "/" -f2)
      bikes=$(bikeAmount "$code")
      echo "$name $bikes"
    done
}

if [ ! -n "$1" ]; then
  showHelp && exit 1
fi 

searchLocation "$1"
